name: "Changelog to Slack"
description: "Receive a `git log` log between two tags and send a message to slack, with hyperlinks, to Jira and Github PRs"
author: rsmartins78
branding:  
  icon: align-justify
  color: white
inputs:
  changeLogFile:
    description: path/name of the text file containing the changelog
    required: true
  jiraTicketPattern:
    description: RegExp to find the Jira Ticket in the commit messages. E.g. 'PROJ-\d+'
    required: true
  jiraURL:
    description: Jira URL used to create the Task URL.
    required: true
  githubServer:
    description: URL to Github server, default to https://github.com
    required: false
    default: https://github.com
  oldVersion:
    description: Old tag version running on the environment
    required: false
    default: "none"
  newVersion:
    description: New tag version running on the environment
    required: false
    default: "none"
  slackBotToken:
    description: Slack Bot Token, required to send messages using WebClient, read more in https://api.slack.com/authentication/token-types#bot
    required: false
    default: "none"
  slackChannel:
    description: Slack Channel to send a message, it can be a channel like '#channel-name' or a user like '@username'
    required: false
    default: "none"
  customSubTitle:
    description: Custom subtitle for the message, can be used say for example the environment that is receiving this update.
    required: false
    default: "none"
outputs:
  formattedChangelog:
    description: "Formatted message, if you prefer to use another action to send the message"
runs:
  using: "node16"
  main: "dist/index.js"
